### ISSUE TITLE
Affect on screen life ?

### ISSUE THREAD

**Issue by intika** [kootenpv/brightml#14]
Hi, 

First thanks for this nice app :+1: 

Does any one know if **changing screen brightness so often** shorten the screen lifespan or create other problems ?

**Details:**

From my general experience (not related to the application) i observed on led device that : 
- Max brightness decrease with time even if technologically it's not intended to decrease
- Variable electricity (not stable) even if used with a charger decrease the lifespan in a huge way
- Blinking leds tend to have a longer lifespan than constant working leds (**BUT** its not always true!) 
- 40% of defect screen that i saw (non physically broken) had back-light not working
- Most of the time leds life is very long, but sometime (7%) it just go off after 1 year of normal usage
- I do also believe that changing the brightness and turning on/off the screen from time to time is good for the screen longevity (my question here is related to changing the brightness that often).
- In theory this should not impact the screen.

(Note that my work involve screens and electronics led devices in a large scale...)

My personal conclusion: 
- Yes it probably affect the screen lifespan **BUT** the impact should be negligible, it's not like loosing 50% of the expected life time.

What do you think, what's your experience ?

**Comment by intika** [comment]
Closing this as side discussion...

**Comment by kootenpv** [comment]
I have no experience. But of course, we are all interested.
